version: '3.8'

services:
  manager:
    build: .
    command: go run ./cmd/manager/main.go
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DATABASE_URL: postgres://testttuser:testttpass@postgres:5432/testttdb?sslmode=disable
      CONFIG_PATH: ${CONFIG_PATH}
    ports:
      - '0.0.0.0:44044:44044'
    volumes:
      - './:/manager'
      - 'go_modules:/go/pkg/mod'
    networks:
      my_custom_network:
        ipv4_address: 5.142.45.67

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/migrations/:/docker-entrypoint-initdb.d/
      - ./data/postgres/:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432"
    networks:
      - my_custom_network

volumes:
  #  rabbitmq_data:
  postgres_data:
  go_modules:

networks:
  my_custom_network:
    driver: bridge
    external: true
